CREATE TABLE sys.authorized_customer_mapping (
	CUSTOMER_ID varchar(100) auto_increment NOT NULL,
	MAPPED_AUTHORIZED_USER_ID varchar(100) NOT NULL,
	AUTHORIZATION_STATUS varchar(100) NOT NULL,
	CREATED_DATE varchar(100) NOT NULL
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci;