CREATE TABLE `customer_cam_mapping` (
  `CUSTOMER_ID` int NOT NULL AUTO_INCREMENT,
  `CAM_ID` varchar(100) NOT NULL,
  `CREATED_DATE` varchar(100) NOT NULL,
  PRIMARY KEY (`CUSTOMER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;