CREATE TABLE `person_detail` (
  `PERSON_ID` int NOT NULL AUTO_INCREMENT,
  `PERSON_NAME` varchar(100) NOT NULL,
  `EMAIL_ID` varchar(100) NOT NULL,
  `PHONE_NUMBER` int NOT NULL,
  `ADDRESS` varchar(100) NOT NULL,
  `PHOTOS` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`PERSON_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;